#!/usr/bin/env dash
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# A simple ccache wrapper to overcome some Semaphore Quirks

# Default distribution ccache path, abort if it doesn't exist
CCACHEBIN=$(command -v ccache || exit 1)

# Check if ccache exists and executable, else? bail out
if [ -x "$CCACHEBIN" ]; then
    $CCACHEBIN "$@"
else
    exit 1
fi