#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Colour Mapping container

BLACK="0"
GREEN="2"
CYAN="6"
RED="1"
PURPLE="5"
LIGHTGRAY="8"
DARKGRAY="233"
LIGHTBLUE="33"
LIGHTGREEN="10"
LIGHTCYAN="51"
LIGHTRED="198"
LIGHTPURPLE="92"
YELLOW="11"
WHITE="15"

colorize() {
	command tput setaf "${@}"
}

decolorize() {
	command tput sgr0
}

# Colorize errors
display_error() {
	echo
	echo "$(tputaf "${RED}")${1}$(tputz)"
	[ -z "${2}" ] && echo
}

# Throw errors in red
die() {
	display_error "${@}"
	exit
}

# Header colorizer
header() {
	if [ -n "${2}" ]; then
		COLOR=${2}
	else
		COLOR=${RED}
	fi
	colorize "${COLOR}"
	echo "====$(for i in $(seq ${#1}); do echo "=\\c"; done)===="
	echo "==  ${1}  =="
	# SC2034: i appears unused. Verify it or export it.
	# shellcheck disable=SC2034
	echo "====$(for i in $(seq ${#1}); do echo "=\\c"; done)===="
	decolorize
}

export BLACK GREEN CYAN RED PURPLE LIGHTBLUE LIGHTGREEN LIGHTCYAN LIGHTRED \
	LIGHTPURPLE YELLOW WHITE DARKGRAY LIGHTGRAY