#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Device Environment container

mido() {
	DEVICE=mido
	DEFCONFIG="raph_defconfig"
	SDM845=false
}

beryllium() {
	DEVICE=beryllium
	DEFCONFIG="raph_beryllium_defconfig"
	SDM845=true
}

dipper() {
	DEVICE=dipper
	DEFCONFIG="raph_dipper_defconfig"
	SDM845=true
}

export DEFCONFIG DEVICE SDM845