#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2019 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.c (the "License");
# you may not use this file except in compliance with the License.
#
# Docker Environment container

docker() {
	ANYKERNEL="$(pwd)/anykernel"
	ZIP_DIR="$(pwd)/files"
	KBUILD_BUILD_USER="raphielscape"
    ZIP_UPLOAD=true
	TERM="xterm-256color"
}

# Some alias
clone() {
	command git clone --depth 1 "${@}"
}

debugtap() {
	tg_debugcast "$(whoami)"
}

export ANYKERNEL ZIP_DIR KBUILD_BUILD_USER TOOLCHAIN ZIP_UPLOAD CROSS_COMPILE TERM