#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2019 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.c (the "License");
# you may not use this file except in compliance with the License.
#
# File operations command container

# Some Relatable Aliases
copy() {
    command cp -R "${@}"
}

delett() {
    command rm -rf "${@}"
}

# Alias echo as teller
echo() {
    command echo -e "${@}"
}
