#!/usr/bin/env bash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Server stack container

function upnet_check() {
    if [ "$(ping -c 1 1.1.1.1)" != "0" ]; then
        echo "Upstream interface is up!";
    else
        echo "Excuse me what the fuck";
    fi
}

function localnet_check() {
    if [ "$(ping -c 1 raphielscape.llc)" != "0" ]; then
        echo "Local interface is up!";
    else
        echo "Nyani?";
    fi
}

function localupdate() {
    sudo pacman -Syuq --noconfirm
}

function kubeupdate() {
    # Rolling update pods
    kubectl rolling-update frontend-v1 -f frontend-v2.json
    # Rename resources and update
    kubectl rolling-update frontend-v1 frontend-v2 --image=image:v2
    # Update pods image
    kubectl rolling-update frontend --image=image:v2
    # Abort existing rollouts
    kubectl rolling-update frontend-v1 frontend-v2 --rollback
    # Replace pods
    cmd pod.json | kubectl replace -f -

    # Force replace, delete and then re-create the resource.
    # Will cause a service outage if this executed in main pod
    kubectl replace --force -f ./pod.json

    # Create a service for a replicated nginx,
    # which serves on port 80 and connects to the containers on port 8000
    kubectl expose rc nginx --port=80 --target-port=8000

    # Update a single-container pod's image version (tag) to v4
    kubectl get pod upstreamkube -o yaml | sed 's/\(image: myimage\):.*$/\1:v4/' | kubectl replace -f -

    kubectl label pods upstreamkube new-label=nyaakube
    kubectl annotate pods upstreamkube icon-url="https://raphielscape.llc/res/nyaakube.png"
    kubectl autoscale deployment nekokube --min=2 --max=10
}

function escapedeath() {
    kubectl delete pod "${@}"
}

function holyfuckingdead() {
    kubectl delete pods "${@}" --grace-period=0 --force
}