#!/usr/bin/env bash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Semaphore Environment container

function semaphorebox() {
	ANYKERNEL="${KERNELDIR}/anykernel"
	ZIP_DIR="${KERNELDIR}/files"
	KBUILD_BUILD_USER="raphielscape"
	TOOLCHAIN="${HOME}/GNU/GCC"
    ZIP_UPLOAD=true
}

# Some alias
function clone() {
	command git clone --depth 1 "${@}"
}

# Toolchain Checks (GCC)
# Our box complaint coz of some reason
if [[ ${WORKER} != raphielbox ]]; then
	function check_gcc_toolchain() {
		TC="$(find "${TOOLCHAIN}"/bin -type f -name "*-gcc")"
		if [[ -f "${TC}" ]]; then
			CROSS_COMPILE="${TOOLCHAIN}/bin/$(echo "${TC}" |
				awk -F '/' '{print $NF}' |
				sed -e 's/gcc//')"
		else
			tg_senderror
			die "No suitable toolchain found in ${TOOLCHAIN}"
		fi
	}
fi

export ANYKERNEL ZIP_DIR KBUILD_BUILD_USER TOOLCHAIN ZIP_UPLOAD CROSS_COMPILE