#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Semaphore Environment container

semaphorebox() {
	ANYKERNEL="${KERNELDIR}/anykernel"
	ZIP_DIR="${KERNELDIR}/files"
	KBUILD_BUILD_USER="raphielscape"
    ZIP_UPLOAD=true
	BUILDURL=$(debuginfo|jq '.build_url'|sed -e 's/^"//' -e 's/"$//')
	START=$(debuginfo|jq '.started_at'|sed -e 's/^"//' -e 's/"$//')
}

# Some alias
clone() {
	command git clone --depth 1 "${@}"
}

debugtap() {
	tg_debugcast "$(whoami)"
}

export ANYKERNEL ZIP_DIR KBUILD_BUILD_USER TOOLCHAIN ZIP_UPLOAD CROSS_COMPILE BUILDURL START