#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Semaphore Environment container

semaphorebox() {
	ANYKERNEL="${KERNELDIR}/anykernel"
	ZIP_DIR="${KERNELDIR}/files"
	KBUILD_BUILD_USER="raphielscape"
	TOOLCHAIN="${HOME}/GNU/GCC"
    ZIP_UPLOAD=true
	BRANCH_ID_MSM8953=2190083
	BRANCH_ID_SDM845=2313683
	BUILDURL=$(debuginfo|jq '.build_url'|sed -e 's/^"//' -e 's/"$//')
	START=$(debuginfo|jq '.started_at'|sed -e 's/^"//' -e 's/"$//')
}

# Some alias
clone() {
	command git clone --depth 1 "${@}"
}

check_gcc_toolchain() {
	TC="$(find "${TOOLCHAIN}"/bin -type f -name "*-gcc")"
	if [ -f "${TC}" ]; then
		CROSS_COMPILE="${TOOLCHAIN}/bin/$(echo "${TC}" |
			awk -F '/' '{print $NF}' |
			sed -e 's/gcc//')"
			header "Using toolchain: $("${CROSS_COMPILE}"gcc --version | head -1)"
	else
		tg_senderror
		die "No suitable toolchain found in ${TOOLCHAIN}"
	fi
}

if [ "${SDM845}" = true ]; then
	debuginfo() {
		curl -s -X GET "https://semaphoreci.com/api/v1/projects/$PROJECT_ID/$BRANCH_ID_SDM845/status?auth_token=$AUTH_TOKEN"
	}
else
	debuginfo() {
		curl -s -X GET "https://semaphoreci.com/api/v1/projects/$PROJECT_ID/$BRANCH_ID_MSM8953/status?auth_token=$AUTH_TOKEN"
	}
fi

debugtap() {
	tg_debugcast "Build Link : ${BUILDURL}" \
		"Started at : <b>${START}</b>"
}

export ANYKERNEL ZIP_DIR KBUILD_BUILD_USER TOOLCHAIN ZIP_UPLOAD CROSS_COMPILE BUILDURL START