#!/usr/bin/env bash
# shellcheck source=/dev/null
#
# Copyright (C) 2019 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.c (the "License");
# you may not use this file except in compliance with the License.
#
# Component stack container

# Include stacks
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/docker
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/colours
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/telegram
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/fileops