#!/usr/bin/env bash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Component stack container

# Include stacks
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/semaphore
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/colours
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/kube