#!/usr/bin/env dash
# shellcheck source=/dev/null
#
# Copyright (C) 2018 Raphielscape LLC.
#
# Licensed under the Raphielscape Public License, Version 1.0 (the "License");
# you may not use this file except in compliance with the License.
#
# Telegram command container

TELEGRAM="${SCRIPTDIR}"/telegram/telegram

# Caster configurations
MAINGROUP_ID="-1001371047577"
BUILDSCAPERER_ID="-1001153251064"
DEBUG_ID="-1001279397127"

# Graphics Interchange Format Assets
Start_Asset="CAADBQADPQIAAp_oJQqaAAHES5FWFaoC"
Stop_Asset="https://i.imgur.com/Q6nllGX.gif"
Jump_Asset="https://i.imgur.com/BO0HlYB.gif"

# GIF Stuff
tg_build_sendsticker() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendSticker" \
    -d sticker="${Start_Asset}" \
    -d chat_id=${BUILDSCAPERER_ID} >> /dev/null
} 

tg_buildmain_sendgif() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendAnimation" \
    -d animation="${Jump_Asset}" \
    -d chat_id=${MAINGROUP_ID} >> /dev/null
}

# Interruption Happen, report with GIF
tg_intgif() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendAnimation" \
    -d animation="${Stop_Asset}" \
    -d chat_id=${BUILDSCAPERER_ID} >> /dev/null
}

tg_intgifmain() {
    curl -s -X POST "https://api.telegram.org/bot$BOT_API_KEY/SendAnimation" \
    -d animation="${Stop_Asset}" \
    -d chat_id=${MAINGROUP_ID} >> /dev/null
}

# Push to Channel
push() {
    "${TELEGRAM}" -f "${ZIP_DIR}/$ZIPNAME" \
    -c ${BUILDSCAPERER_ID}
}

# sendcast to group
tg_sendinfo() {
    "${TELEGRAM}" -c ${MAINGROUP_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )"
}

# sendcast to channel
tg_channelcast() {
    "${TELEGRAM}" -c ${BUILDSCAPERER_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )"
}

# Debugcasting
tg_debugcast() {
    "${TELEGRAM}" -c ${DEBUG_ID} -H \
    "$(
		for POST in "${@}"; do
			echo "${POST}"
		done
    )"
}

kickstart() {
    tg_buildmain_sendgif
    tg_build_sendsticker
    
    tg_channelcast "Compiler <code>${COMPILER_USED}</code>" \
    "Device <b>${DEVICE}</b>" \
    "Branch <code>${PARSE_BRANCH}</code>" \
    "Commit Point <code>${COMMIT_POINT}</code>" \
    "Under <code>$(hostname)</code>" \
    "Started on <code>$(whoami)</code>"
}